application: guest-book-kg
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /.*
  script: main.application
  static_files: favicon.ico
  upload: favicon\.ico

libraries:
- name: webapp2
  version: "2.5.2"
