#!/bin/bash

read -p "Enter song search: " song
read -p "Enter save title: " title
read -p "Enter radio frequency: " freq


youtube-dl -x "$song" --no-playlist --audio-format mp3 -o "~/Music/YTDL/$title.%(ext)s"

sox -v .9 -t mp3 ~/Music/YTDL/$title.mp3 -t wav --input-buffer 80000 -r 22050 -c 1 - | sudo ./pifm - $freq

read -p "Delete song? (y/N) " yn
if [[ $yn == "y" ]]
then
	rm ~/Music/YTDL/$title.*
else
	python ~/Applications/BashTube/cleanupMP3.py
fi
