#!/bin/bash

read -p "Enter song search: " song
read -p "Enter save title: " title
read -p "Enter radio frequency: " freq


youtube-dl -x "$song" --no-playlist --audio-format mp3 -o "/home/pi/Music/YTDL/$title.%(ext)s"

sox -v .9 -t mp3 "/home/pi/Music/YTDL/$title.mp3" -t wav --input-buffer 80000 -r 22050 -c 1 - | sudo ~/Applications/PiFM/pifm - $freq

read -p "Delete song? (y/N) " yn
if [[ $yn == "y" ]]
then
	rm "/home/pi/Music/YTDL/$title.mp3"
else
	python ./cleanupMP3.py
fi
