#!/bin/bash

read -p "Enter song search: " song
read -p "Enter save title: " title

youtube-dl -x "$song" --no-playlist --audio-format mp3 -o "/home/pi/Music/YTDL/$title.%(ext)s"
mpg321 "/home/pi/Music/YTDL/$title.mp3"
read -p "Delete song? (y/N) " yn
if [[ $yn == "y" ]]
then
	rm "/home/pi/Music/YTDL/$title.mp3"
else
	python ./cleanupMP3.py
fi
